name: Deploy Dockerized React App
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
  
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test 
    
  build-and-push:
    env: 
      AWS_ENV_NAME: 'Samplereactdockerapp-env'
      AWS_APP_NAME: 'sample-react-docker-app'
      AWS_REGION: 'us-east-1'

    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get code  
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login into Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Tag Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ github.actor }}/sample-react-docker-app:${{ github.sha }}

      - name: Generate ZIP
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy ZIP to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: sample-react-docker-app
          environment_name: Samplereactdockerapp-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
          existing_bucket_name: elasticbeanstalk-us-east-1-872767302345
          use_existing_version_if_available: true
        

      
      


